'use client';

import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';
import { publishRecap, unpublishRecap } from './actions';

type RecapPublishPanelProps = {
  sessionId: string;
  figureSlug: string;
  figureName: string;
  roomSlug: string;
  roomTitle: string;
  revalidatePath: string;
};

export function RecapPublishPanel({
  sessionId,
  figureSlug,
  figureName,
  roomSlug,
  roomTitle,
  revalidatePath,
}: RecapPublishPanelProps) {
  const shortSession = sessionId.slice(0, 8);
  const slug = `${figureSlug}-${roomSlug}-${shortSession}`;

  return (
    <Card>
      <CardHeader>
        <CardTitle className="text-base">Public recap</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4 text-sm text-slate-700">
        <p>
          Publish a public recap summary to show a curated view of the conversation on the recap
          page. You can leave the summary blank to rely on the autogenerated version.
        </p>

        <form action={publishRecap} className="space-y-3">
          <input type="hidden" name="session_id" value={sessionId} />
          <input type="hidden" name="figure_slug" value={figureSlug} />
          <input type="hidden" name="room_slug" value={roomSlug} />
          <input type="hidden" name="public_figure_name" value={figureName} />
          <input type="hidden" name="room_title" value={roomTitle} />
          <input type="hidden" name="revalidate" value={revalidatePath} />

          <Textarea
            id="public-recap-summary"
            name="summary"
            rows={3}
            placeholder="Summarize the biggest takeaways (optional)"
            className="text-sm"
          />

          <Button type="submit" variant="default">
            Publish recap
          </Button>
        </form>

        <form action={unpublishRecap} className="space-y-2">
          <input type="hidden" name="session_id" value={sessionId} />
          <input type="hidden" name="slug" value={slug} />
          <input type="hidden" name="revalidate" value={revalidatePath} />
          <Button type="submit" variant="outline">
            Unpublish recap
          </Button>
        </form>
      </CardContent>
    </Card>
  );
}
